### ISSUE TITLE
Bug: Missing intro text

### ISSUE THREAD

**Issue by Jongmassey** [ebmdatalab/outliers#11]
>This is some intro text.

Needs better preamble written or this dummy text removed.

**Comment by brianmackenna** [comment]
As per previous chats in DataLab we prefer first drafts of substantial text to be done in google docs so everyone can contribute/comment quickly. Once this is done we can convert for site

https://docs.google.com/document/d/1F6VdCoTBKcNl3AS9RNEYDos2_yYUT3cj8VTKRmWppYA/edit?usp=sharing
