### ISSUE TITLE
Organisations to display

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/outliers#17]
Do we want to display all organisations that we show on main OP? i.e. practice, PCN, CCG, ICS, Region 

Yes if possible but for discussion if we need to prioritise.

**Comment by Jongmassey** [comment]
Appears these are available in the [CCGs table](https://console.cloud.google.com/bigquery?utm_source=bqui&utm_medium=link&utm_campaign=classic&project=ebmdatalab&d=hscic&p=ebmdatalab&t=ccgs&page=table&ws=!1m30!1m4!4m3!1sebmdatalab!2shscic!3spractices!1m4!4m3!1sebmdatalab!2shscic!3sstps!1m4!4m3!1sebmdatalab!2spublic_draft!3sstp!1m4!4m3!1sebmdatalab!2saggregated_data!3spractices_and_ccgs_in_prescribing!1m4!4m3!1sebmdatalab!2shscic!3sccg_mapping!1m4!4m3!1sebmdatalab!2shscic!3sccgs). If we join practice to this then that'll enable grouping by STP/Region

**Comment by Jongmassey** [comment]
Does this still need region level added or can it now be closed?

**Comment by brianmackenna** [comment]
I think we don't need it now but we may want to revisit if we integrate into the main site - I think close for this reason? Or do we leave open until then?

**Comment by Jongmassey** [comment]
Happy to leave open, just wanted to be sure there wasn't something that needed doing right away

**Comment by brianmackenna** [comment]
Closing. Actually better to approach it fresh or see what feedback comes in from users

**Comment by brianmackenna** [comment]
you also added all the other ones in so nice to tick off the list!
