### ISSUE TITLE
Review of test_outliers.py

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/outliers#2]
@CarolineMorton you asked me to review your test -- it all looks sensible and looks like it could pick up some bugs in the code.  I'm a big fan of your approach of testing that a function works by implementing it a second way, and testing that both functions give the same result.

A couple of minor things:

* I'd like to see an example of the kind of thing that `make_fake_data()` would return -- you can work it out by reading the code, but that requires extra thinking
* In `alternate_get_stats()`, you never use `a_num`, `b_num`, or `b_list`

**Comment by CarolineMorton** [comment]
hi @inglesp 

thanks for this. I will make the changes in alternative_get_stats(). When you say about make_fake_data... do you want the example data set printed to the terminal or put somewhere else for example the documentation.

**Comment by inglesp** [comment]
I'd thought the example data could be included in the docstring for `make_fake_data()`.
