### ISSUE TITLE
Link to organisation members - not the organisation

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/outliers#26]
Currently the hyperlinks from an [organisation page](https://raw.githack.com/ebmdatalab/outliers/master/data/html/static_ccg_00N.html) link to the analyse page to display it compared to their peers ([South Tyneside CCG example](https://openprescribing.net/analyse/#org=CCG&orgIds=00N&numIds=1308010U0&denomIds=13.8.1&selectedTab=summary))

This will always show them as extreme outlier by definition and it is not giving them much extra information on the landing page (it does give time series which might be useful).

I propose that we [generate the link](https://openprescribing.net/analyse/#org=practice&orgIds=00N&numIds=1308010U0&denomIds=13.8.1&selectedTab=summary) to it takes them to the analyse page where it displays their members so in the South Tyneside example above the landing page shows the CCG user immediately that the outlier relates to a single practice.

@richiecroker  you may have thoughts on preferred link. 

NB I don't think the feature of displaying members works at every organisation level which is referred to in this issue https://github.com/ebmdatalab/openprescribing/issues/2281 (i'm not proposing we do any work on #2281 right now - only implement it for orgs where feature currently works)

**Comment by Jongmassey** [comment]
This should be relatively easy to do with the hierarchical structure that exists to support the table of contents. Is it the case the link should always go one layer down (i.e STP->CCG, CCG->PCN, PCN->Practices) or should it always just go to practice (or bespoke rules of each layer)?

**Comment by brianmackenna** [comment]
It actually only works for ccg->practice. probably to faffy to amend it just for this level but not the others?

**Comment by Jongmassey** [comment]
Not overly so
