### ISSUE TITLE
Feedback form Amendments

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/outliers#34]
The following is to collect observations about the feedback form

- ~Add question: I wonder should me ask a person their role? e.g. doctor v prescribing adviser v head of MO?~
- ~_edit_ #26   - i had to change this setting with ever single graph while reviewing all questions.~
- Balance of the form is not weighed towards individual items. Lets see what others come back with but I think we should split feedback on the individual items into at least two separate questions (one for higher one for lower)

**Comment by brianmackenna** [comment]
Additional suggestion

> what features or additions would help improve usability or utility

**Comment by Jongmassey** [comment]
re #17 what setting is that?

**Comment by brianmackenna** [comment]
Apologies that should've linked to #26

**Comment by brianmackenna** [comment]
All done
